import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-gray-100  ">
        <header>

        <Header></Header>
        </header>
        <main className="ml-24 mr-5 pt-16"> {children}

          <Footer></Footer>
        </main>
      </body>
    </html >
  );
}
