import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-gray-100  ">
        <Header></Header>
        <main className="ml-16"> {children}</main>
      </body>
    </html >
  );
}
